### ISSUE TITLE
Buttons' css is refreshed onChange

### ISSUE THREAD

**Issue by Blackbaud-MarybelArcher** [blackbaud/skyux-inline-form#6]
### Expected behavior
Dynamic buttons' style would be ideal.
### Actual behavior
Buttons' css is only applied on form's init
### Steps to reproduce
It doesn't matter how many changes are made to the form, buttons's style cannot be modified even when buttons's config is read multiple times.
### Impact
Functionality to make button's dynamic needs to be implemented by each form client.

**Comment by Blackbaud-IsaacAggrey** [comment]
To add some more clarity to this issue - you can't dynamically change the buttons based on the state of the consuming component, which is a direct use case from a decided upon UX design pattern. It requires nearly 100 lines and direct `ElementRef` usage to hack around this by directly manipulating the elements.

Can we revisit the severity of this issue?

**Comment by Blackbaud-SteveBrush** [comment]
Related: https://github.com/blackbaud/skyux-inline-form/issues/7

**Comment by Blackbaud-AlexKingman** [comment]
This functionality is now available as of version `3.0.1`. Consumers should be able to push style changes to the buttons via the `SkyInlineFormButtonConfig` object.

Also of note, version `3.1.0` provides the ability to disable buttons as well.
